version: 3


includes:
  frontend:
    taskfile: ./devoxx-frontend/Taskfile.yml
    dir: ./devoxx-frontend
  backend:
    taskfile: ./taskfile.go.yml
    dir: ./devoxx-backend
    vars:
      GENERATE: golang-server
  cli:
    taskfile: ./taskfile.go.yml
    dir: ./devoxx-cli
    vars:
      GENERATE: cli


tasks:
  hello:
    cmds:
      - echo "hello world"
      - echo "1"

  hello2:
    cmd: echo "Hello world"

  hello3: echo "hello worlddd"

  deploy:
    deps:
      - frontend:build
      - backend:build
    internal: true
    requires:
      vars:
        - ENV
    preconditions:
      - sh : command -v terraform
        msg : "You need to have terraform installed"
    cmds:
      - echo "Deploying {{.ENV}}"

  deploy/dev:
    cmds:
      - task: deploy
        vars: { ENV: dev }

  deploy/beta:
    cmds:
      - task: deploy
        vars: { ENV: beta }

  deploy/prod:
    prompt: "You are sure to deploy to prod ?"
    cmds:
      - task: deploy
        vars: { ENV: prod }


