version: 3

tasks:
  hello:
    cmds:
      - echo "hello world"
      - echo "1"

  hello2:
    cmd: echo "Hello world"

  hello3: echo "hello worlddd"

  deploy:
    internal: true
    requires:
      vars:
        - ENV
    preconditions:
      - sh : command -v terraform
        msg : "You need to have terraform installed"
    cmds:
      - echo "Deploying {{.ENV}}"

  deploy/dev:
    cmds:
      - task: deploy
        vars: { ENV: dev }

  deploy/beta:
    cmds:
      - task: deploy
        vars: { ENV: beta }

  deploy/prod:
    prompt: "You are sure to deploy to prod ?"
    cmds:
      - task: deploy
        vars: { ENV: prod }


